News/urls.py
from django.urls import path,re_path
from . import views


urlpatterns=[

	path('',views.LatestNewsView.as_view(template_name='news.html'),name='news-list'),
	# path('skysports/<str:path>/',views.scrawler,name='skysports'),	
	# path('espn/<str:path>/',views.ecrawler,name='espnfc'),
	path('<int:pk>/',views.NewsDetailView.as_view(),name='news-detail'),
	path('<slug:slug>',views.NewsRedirectView.as_view(),name='news-portal'),

]

Players/urls.py
from django.urls import path,re_path
from .views import PlayerView,PlayersListView,ThanksView,PlayerPollView,PlayerDetailView,PlayerNationalityView
from django.views.decorators.cache import cache_page
from . import views


urlpatterns=[

    path('',PlayersListView.as_view(),name='players-main-page'),   	
    path('polls/',PlayerPollView.as_view(),name='players-by-vote'),
    path('thanks/',ThanksView.as_view()),
    path('country/<str:name>',views.PlayerNationalityView.as_view(),name='player-by-nationality'),
    path('countries/<str:page_num>/',views.Countries.as_view(),name='Countries'),
   	path('<slug:pk>/',views.PlayerDetailView.as_view(),name='players-by-name'),
   	path('<str:id>/',PlayerView.as_view(),name='players-by-id'),

]

Projectfootball/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from . import views
from django.views.generic.base import TemplateView

urlpatterns = [
	
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),


]

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/',include('rosetta.urls')),
    ]


urlpatterns += i18n_patterns(
    path('', TemplateView.as_view(template_name="homepage.html"), name='home'),
    path('about/',TemplateView.as_view(template_name="info.html"),name='about'),
    path('news/',include('News.urls')),
    path('players/',include('Players.urls')),
    path('assorted/',include('assortedApps.urls')),
    path('search/',views.Search,name='search'),

)

News/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class News(models.Model):

	user=models.ForeignKey(User,on_delete=models.CASCADE,verbose_name="USER")
	headline=models.CharField(verbose_name="HEADLINE",max_length=100,blank=False,null=True)
	byline=models.CharField(verbose_name="WRITER",max_length=20)
	content=models.TextField(verbose_name="CONTENT",blank=False,max_length=10000,null=True)
	date_published=models.DateField(verbose_name="DATE PUBLISHED",default=timezone.now,null=True)
	source=models.CharField(verbose_name="SOURCE",max_length=500,null=True)
	category=models.CharField(choices=
									(
									('TN','Transfer News'),
									(
									'Leagues And Tournaments',
										(
										('EURO','EURO'),
										('UCL','UEFA CHAMPIONS LEAGUE'),
										('ESP','SPAIN'),
										('ENG','ENGLAND'),
										('FRA','FRANCE'),
										('ITA','ITALY'),	
										('GER','GERMANY'),			
										)
									),

									('MD','Matchday Analysis'),
									),max_length=10,blank=False,verbose_name="CATEGORY")
	


	class Meta:
		db_table='news_info'
		verbose_name='New'

Players/models.py
from django.db import models

#Create your models here.

class Country(models.Model):

	country_name=models.CharField(max_length=20,blank=False,verbose_name='COUNTRY')
	capital_city=models.CharField(max_length=20,blank=False,verbose_name='CAPITAL')
	continent=models.CharField(choices=(
										('EUROPE','EUROPE'),
			 							('SOUTH AMERICA','SOUTH AMERICA'),
										('NORTH AMERICA','NORTH AMERICA'),
										('AUSTRALIA','AUSTRALIA & OCENIA'),
										('ASIA','ASIA'),
										('AFRICA','AFRICA'), 
									   ),max_length=20,blank=False,verbose_name='CONTINENT')
	
	def __str__(self):
		return self.country_name

	class Meta:
		db_table='country_info'
		verbose_name='Country Information'

class PlayerData(models.Model):
	position_choices=(
			('GK','Goalkeeper'),
			(
				'Defender',
						(
						('CD','Central Defender'),
						('RCD','Right Central Defender'),	
						('LCD','Left Central Defender'),
						('RF','Right Full Back'),
						('LF','Left Full Back')
						)
			),

			(	
				'MidFielder',
						(
						('DM','Defensive MidFielder'),
						('B2B','Box To Box MidFielder'),	
						('CM','Central MidFielder'),
						('RCB','Right Central MidFielder'),
						('LM','Left Offensive MidFielder'),
						('OM','Offensive MidFielder'),
						('RM','Right Offensive MidFielder'),
						('PM','PlayerMaker'),
						)
			),

			(
				'Forward',
						(
						('ST','Striker'),
						('RW','Right Winger'),	
						('LW','Left Winger'),
						('CF','Centre Forward'),
						)
			)

			
			
			)

	player_name=models.CharField(verbose_name="FIRST NAME",max_length=30,blank=False)
	full_name=models.CharField(verbose_name="FULL NAME",max_length=30,blank=True)
	age=models.IntegerField(verbose_name="AGE",default=0,blank=False)
	player_height=models.DecimalField(verbose_name="HEIGHT(m)",default=0,blank=True,decimal_places=2,max_digits=4)
	player_weight=models.DecimalField(verbose_name="WEIGHT(kg)",default=0,blank=True,decimal_places=2,max_digits=4)
	player_nationality=models.ForeignKey(Country,on_delete=models.PROTECT,verbose_name="NATIONALITY")
	player_position=models.CharField(choices=position_choices,verbose_name="FIELD POSITION",max_length=15,blank=False,default="None")
	shirt_num=models.IntegerField(verbose_name="SHIRT NUMBER",blank=True,null=True)


	def __str__(self):
		return self.player_name

	class Meta:
		db_table='playerdata'
		verbose_name='Player'

class ManagerData(models.Model):
	manager_name=models.CharField(verbose_name="FULL NAME",max_length=30,blank=True)
	date_of_birth=models.DateField(verbose_name="DATE OF BIRTH")
	manager_nationality=models.ForeignKey(Country,on_delete=models.CASCADE,verbose_name="NATIONALITY")


	def __str__(self):
		return self.manager_name

	class Meta:
		db_table='managerdata'
		verbose_name='Manager'

News/forms.py
from django import forms
from django.utils.translation import gettext as _

class DateInput(forms.DateInput):
	input_type='date'
		
class DateForm(forms.Form):
	date_published=forms.DateField(widget=DateInput,label=_("Choose the preferred news date (required, from 2021 April 1 to June 14)"))

Players/forms.py
from django import forms

class NameForm(forms.Form):
	your_name = forms.CharField(label='Your name', max_length=100)

# import requests, uuid, json

# # Add your subscription key and endpoint
# subscription_key = "aeae4eb5841c44bbb965a93fa6bda34a"
# endpoint = "https://api.cognitive.microsofttranslator.com"

# # Add your location, also known as region. The default is global.
# # This is required if using a Cognitive Services resource.
# location = "global"

# path = '/translate'
# constructed_url = endpoint + path

# params = {
#     'api-version': '3.0',
#     'from': 'en',
#     'to': ['fr', 'it']
# }
# constructed_url = endpoint + path

# headers = {
#     'Ocp-Apim-Subscription-Key': subscription_key,
#     'Ocp-Apim-Subscription-Region': location,
#     'Content-type': 'application/json',
#     'X-ClientTraceId': str(uuid.uuid4())
# }

# # You can pass more than one object in body.
# body = [{
#     'text': 'Hello'
# }]

# request = requests.post(constructed_url, params=params, headers=headers, json=body)
# response = request.json()

# print(json.dumps(response, sort_keys=True, ensure_ascii=False, indent=4, separators=(',', ': ')))

News/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpRequest
from django.utils.decorators import method_decorator
from django.utils import timezone
from django.views.decorators.http import require_http_methods
from django.contrib.postgres.search import SearchVector,SearchQuery,SearchRank
from django.views.decorators.cache import cache_page
from django.views.generic.base import View,RedirectView
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView
from .models import News 
from .forms import DateForm
from datetime import date
import requests,uuid,json
from bs4 import BeautifulSoup

class Crawler:
	'''A News Class'''
	def __init__(self,headline,caption='',path='',content='',inner_headline='',timestamp='',author='',category=''):
		self.headline=headline
		self.path=path
		self.content=content
		self.inner_headline=inner_headline
		self.timestamp=timestamp
		self.author=author
		self.caption=caption
		self.category=category


class NewsRedirectView(RedirectView):
	url='/News'


class NewsDetailView(DetailView):
	model=News


class LatestNewsView(ListView,FormView):

	#snippets=[]
	model=News
	paginate_by=10
	success_url='/News'
	form_class=DateForm

	
	def get_context_data(self,**kwargs):

		context=super().get_context_data(**kwargs)
		""" source = requests.get('https://www.skysports.com/football/news').text
		soup = BeautifulSoup(source,'lxml')

		for snippet in soup.find_all('div',class_='news-list__body'):
			
			headline = snippet.find('h4',class_='news-list__headline').text
			category =snippet.find('a', class_='label__tag').text
			timestamp =snippet.find('span', class_='label__timestamp').text
			content = snippet.find('p',class_='news-list__snippet').text
			link_src= snippet.find('a',class_='news-list__headline-link')['href']
			path=link_src.replace('/','#')

			self.snippets.append(Crawler(headline=headline,content=content,category=category,timestamp=timestamp,path=path))

		context['scraped_news']=self.snippets """
		context['recent_news']=News.objects.all()
		
		return context

	def post(self,request):

		form=DateForm(request.POST)

		if form.is_valid():
			date_input=form.cleaned_data['date_published']
			filtered_news=News.objects.filter(date_published__exact=date_input)
			context={'filtered_news':filtered_news}
			return render(request,'newsevent.html',context)

""" #@cache_page(60*15)
def scrawler(request,path):

	news_object = []
	content = []
	news_object.clear()
	content.clear()

	path = path.replace('#','/')
	source = requests.get(path).text		
	soup = BeautifulSoup(source,'lxml')

	#Scraping Useful Data
	header=soup.find('h1',class_='sdc-site-component-header--h1 sdc-article-header__title').text
	subtitle=soup.find('p',class_='sdc-site-component-header--h2 sdc-article-header__sub-title').text
		
	try:
		byline=soup.find('p',class_='sdc-article-author__byline')
	
	except(AttributeError):
		byline = 'None'

	datetime=soup.find('p',class_='sdc-article-date__date-time').text	
	body_div=soup.find('div',class_='sdc-article-body sdc-article-body--lead')
	for element in body_div.find_all('p'):
		content.append(element.text)

	news_object.append(Crawler(headline=header,content=content,caption=subtitle,timestamp=datetime,author=byline))

	context={
			'scraped_news':news_object
			}

	return render(request , 'News/newspage.html' , context)


#@cache_page(60*2)
def ecrawler(request,path):

	news_object = []
	content = []
	news_object.clear()
	content.clear()

	path = path.replace('#','/')
	url = 'https://www.espn.in/'+path
	source = requests.get(url).text
	soup = BeautifulSoup(source,'lxml')

	#Scraping Useful Data
	article = soup.find('section',class_='col-b')
	headline = article.find('h1').text
	article_meta = soup.find('div',class_='article-meta')
	timestamp = article_meta.find('span',class_='timestamp').text
	author = article_meta.find('div',class_='author').text

	for item in article.find_all('p'):
		content.append(item.text)

	news_object.append(Crawler(headline=headline,content=content,timestamp=timestamp,author=author))

	context={
			'scraped_news':news_object
			}

	return render(request , 'News/newspage.html' , context) """

Players/views.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.shortcuts import render
from django.utils.translation import gettext as _
from django.utils.translation import get_language, activate
from django.views import View
from django.http import HttpResponseRedirect,HttpResponse,HttpResponseNotFound,Http404,HttpResponseServerError
from django.views.generic.base import TemplateView
from django.views.generic import ListView,DetailView
from django.views.generic.edit import FormView
from .forms import NameForm
from .models import PlayerData,Country
from apikeys import key_elena
import requests
# Create your views here.

#Class Based View

class PlayersListView(ListView):
	paginate_by=50
	template_name='PlayersList.html'
	context_object_name='playerslist'
	model=PlayerData


class PlayerDetailView(DetailView):

	model=PlayerData
	template_name="Player.html"
	context_object_name="playerdetails"

	def get_context_data(self,*args,**kwargs):

		context=super().get_context_data(*args,**kwargs)
		context['data']=PlayerData.objects.all()
		return context 

class PlayerView(View):
	
	def get(self,request,id):

		try:
			secret_key=key_elena.restrictedFunction()
			url = "https://football.elenasport.io/v2/players/"+id
			payload={}
			headers = {
	  					'Authorization': secret_key
						}
			response = requests.request("GET", url, headers=headers, data=payload)
			playerdata=response.json()
			context={
					'name':playerdata['data'][0]['name'],
					'nationalities':playerdata['data'][0]['nationalities'][0],
					'fullName':playerdata['data'][0]['fullName'],
					'pob':playerdata['data'][0]['pob'],
					'dob':playerdata['data'][0]['dob'],
					'height':playerdata['data'][0]['height'],
					'weight':playerdata['data'][0]['weight'],
					'foot':playerdata['data'][0]['foot'],
					'photoURL':playerdata['data'][0]['photoURL'],
					}
			return render(request,'Player.html',context)

		except ConnectionError:
			raise HttpResponse("Sorry!")


class PlayerPollView(FormView):

	form_class=NameForm
	template_name="Polls.html"
	success_url="/Players/thanks/"

	def form_valid(self,form):
		print(form.cleaned_data)
		return super().form_valid(form)


class ThanksView(TemplateView):

	template_name="thanks.html"


class PlayerNationalityView(TemplateView):
 	template_name='PlayersList.html'
 	paginate_by=3

 	def get_context_data(self,name,*args,**kwargs):
 		context=super().get_context_data(*args,**kwargs)
 		c=Country.objects.filter(country_name=name)
 		context['playerslist']=PlayerData.objects.filter(player_nationality_id=c[0].id)
 		return context

#@cache_page(60*1)

class Countries(View):


	def get(self,request,page_num):
		

		#try:
			secret_key=key_elena.restrictedFunction()
			url="https://football.elenasport.io/v2/countries?page="+page_num
			payload={}
			headers = {
					  	'Authorization': secret_key
					}
			response = requests.request("GET", url, headers=headers, data=payload)
			context=response.json()

			return render(request,'Countries.html',context)

		#except requests.exceptions.ConnectionError:

		#	raise HttpResponseServerError()








#@method_decorator(login_required,name='dispatch')
#class ProtectedView(TemplateView):
#	paginate_by=10
#	template_name='secret.html'






	

templates/Countries.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
	<title>Nations</title>
	<link rel="stylesheet" type="text/css" href="{% static 'Countries.css' %}">
	<link rel="icon" href="{% static 'Football tracker.png' %}" type="image/icon type">
</head>

<body>
	<h2 style="position: sticky;">Click a Flag to Filter Players</h2>
	
	<div id="flex-container">
		
		
		{% for value in data %}
		

	<div id="main">

		
		<a href="{% url 'player-by-nationality' value.name %}"><img src="{{value.flag}}" height="25%"><br></a>
		<div id="Name">Name: {{value.name}}</div><br>
		<div id="Capital">Capital: {{value.capital}}</div><br>
		<div id="Region">Region: {{value.region}}</div><br>
		<div id="Subregion">Subregion: {{value.subregion}}</div><br>
		<div id="Timezones">Timezones: {{value.timezones}}</div><br>

	</div>
		{% endfor %}

	</div>
	

	<footer>
		
		{% if pagination.hasPrevPage %}	
			<a href="{% url 'Countries' pagination.page|add:'-1' %}">&laquo; Back</a>
		{% endif %}

		{% if pagination.hasNextPage %}	
			<a href="{% url 'Countries' pagination.page|add:'1'  %}">Next &raquo;</a>
		{% endif %}

	</footer>
	

</body>

</html>

templates/Leagues.html
<!DOCTYPE html>
<html>
	{% load static %}
<head>
	<meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{% block title %}Scoreboard{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'League.css' %}">
	<link rel="icon" href="{% static 'Football tracker.png' %}" type="image/icon type">

</head>
<body>
	
	<h1><span><img src="{% static 'Logooo.png' %}" alt="The Footballtracker logo"></span>Football Tracker</h1>

	
	<div class="outer">
		<button onclick="#">Home</button><br>
		<button onclick="#">Spain</button><br>
		<button onclick="#">England</button><br>
		<button onclick="#">France</button><br>
		<button onclick="#">Italy</button><br>
		<button onclick="#">Germany</button><br>
		<button onclick="#">Netherlands</button><br>
		<button onclick="#">Scotland</button><br>
		<button onclick="#">Uefa Champions League</button><br>
		<button onclick="#">Europa League</button><br>
		<button onclick="#">Euro 2020</button><br>
		<button onclick="#">World Cup</button><br>
		<button onclick="#">UEFA Nations League</button><br>
		<button onclick="#">African Cup of Nations</button><br>
		<button onclick="#">Copa America</button><br>
		<button onclick="#">Women's Euro</button><br>
		<button onclick="#">Euro U21</button><br>
		<button onclick="#">CONACAF</button><br>
		<button onclick="#">International</button><br>



	<span class="specialbutton"><button>Other Options</button>
	<div class="dropdown-content">
	
	{% for item in country_list %}
	<button class="inner-special">{{item.country_name}}</button><br>
	{% endfor %}
	</div>
	
	</span>

	</div>


	
	
	<div class="fixtures">


    {% block league %}
			
			<div class="league-divison"><h1>ONGOING MATCHES<h1></div>		
				
			{% for value in matches.data|dictsort:"match_start" %}
				<div class="matches">
				{% if value.status == "finished" %}
					<h5><span> {{value.stats.home_score}} <img  src={{value.home_team.logo}}>
					{{ value.home_team.name }}{{value.country.country_code}}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ value.away_team.name}}{{value.country.country_code}}
					<img  src={{value.away_team.logo}}> {{value.stats.away_score}}</span></h5>

				{% else %}
					<h5>{{value.match_start}}<h2><h1><span>&nbsp;&nbsp;<img src={{value.home_team.logo}} > 
					{{ value.home_team.name }}&nbsp;&nbsp;&nbsp;VS&nbsp;&nbsp;&nbsp;{{ value.away_team.name }}
					<img  src={{value.away_team.logo}}></span></h5>
				{% endif %}	

				<a href="#" align="left">View Details</a>
			</div>
			{% endfor %}


	{% endblock %}

	</div>

	

	

	<div class="head">
		
		<table>
			<div class="inner">
	 			 Points Table
			</div>
		<tr>

			<th colspan="3 "width=70%>Team</th>
			<th>MP</th>
			<th>Pts</th>

		</tr>

{% block table %}
		{% for team in data %}

		<tr>
		<td>{{1}}</td>
		<td colspan="2" width="60%"></td>
		<td>{{38}}</td>
		<td>{{77}}</td>
		</tr>
		
		{% endfor %}
{% endblock %}

		

		</table>


	</div>

	

		

	


<!--

	
		
	{% for league in data %}
	<li>
		<ul>
			
			<li>{{id}}</li>
			<li>{{idCountry}}</li>
			<li>{{countryName}}</li>
			<li>{{nationalLeague}}</li>
			<li>{{clubsLeague}}</li>
			<li>{{name}}</li>

		</ul>
	</li>

	<p>The information are fetched through REST Api's. So, any </p>

	{% endfor %}-->

	<footer>
		
		<p>The information are fetched through REST Api's. So, server failures may frequently arrive.</p>

	</footer>
</body>
</html>

templates/Player.html
<!DOCTYPE html>
<html>
<head>
	<title>Footballing|Player</title>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'Player.css' %}">
	<link rel="icon" href="{% static 'Football tracker.png' %}" type="image/icon type">
</head>

<body>
	Player Information Display Page
	<div id="main">
		<img src="{{photoURL}}"><br>
		<div id="name">Name: {{player_name}}</div><br>
		<div id="nationalities">Nationality: {{nationalities}}</div><br>
		<div id="fullName">Full Name: {{fullName}}</div><br>
		<div id="pob">Place of Birth: {{pob}}</div><br>
		<div id="dob">Date of Birth: {{dob}}</div><br>
		<div id="height">Height: {{height}}</div><br>
		<div id="weight">Weight: {{weight}}</div><br>
		<div id="foot">Foot: {{foot}}</div><br>
	</div>
</body>
</html>

templates/PlayersList.html
{% extends 'homepage.html' %}
{% block title %}Footballers{% endblock %}
{% load i18n %}
{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'PlayersList.css' %}">

<!--<div class="players-info">

    <h3 style="text-align: center;">List of the players</h3>
        <table>
            <tr>
              <th>{% translate 'Player name' %}</th>
              <th>{% translate 'Full name' %}</th>
              <th>{% translate 'Age' %}</th>
              <th>{% translate 'Height' %}</th>
              <th>{% translate 'Weight' %}</th>
            </tr>
            {% for player in playerslist %}
            <tr>
              <td>{{player.player_name}}</td>
              <td>{{player.full_name}}</td>
              <td>{{player.age}}</td>
              <td>{{player.player_height}}</td>
              <td>{{player.player_weight}}</td>
            </tr>
            {% endfor %}
            
          </table>
</div>-->

<div class="body_tag">
    
    <div class="team">

      {% for player in playerslist %}
      <div class="team_member">
        <div class="team_img">
          <img src="{% static 'boot.jpeg' %}" alt="Player_image">
        </div>
        <h3>{{player.player_name}}</h3>
        <p class="role"><p>Field Position : {{player.player_position}}</p></p>
        <p>
          Name : {% if player.full_name %}
          {{player.full_name}}
          {% else %}
          Not available
        {% endif %}
      </p>
        <p>Age : {{player.age}}</p>
        <p>Height : {{player.player_height}}</p>
        <p>Weight : {{player.player_weight}}</p>
        <p>Nationality : {{player.player_nationality}}</p>
      </div>
      {% endfor %}
      
</div>


<div class="paginator">
  
<span class='step-links'>
  

{% if page_obj.has_previous %}

<a href="?page=1">&laquo; first</a>

<a href="?page={{page_obj.previous_page_number}}">{% translate 'previous' %}</a>

{% endif %}


<span class="current">

{% translate 'Page' %} {{page_obj.number}} {% translate 'of' %} {{page_obj.paginator.num_pages}}

</span>


{% if page_obj.has_next %} 

<a href="?page={{page_obj.next_page_number}}">{% translate 'next' %}</a>
<a href="?page={{ page_obj.paginator.num_pages }}">{% translate 'last' %} &raquo;</a>


{% endif %}


</span>

</div>

</div>

{% endblock %}

templates/PointsTable.html
{% extends 'homepage.html' %}
{% load i18n %}
{% block title %}Points Table{% endblock %}


{% block content %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'PointsTable.css' %}">

<meta http-equiv="X-UA-Compatible" content="IE=edge">

	
<!-- neew -->



<div class="gridds-1">

  <div class="gri1-1">

      <button> <li><a href="{% url 'moreSpecificLeagueView'  'UCL'%}">UEFA Champions League</a></li></button>

      <button> <li><a href="{% url 'moreSpecificLeagueView'  'Laliga' %}">Laliga Santander</a></li></button>
     
      <button> <li><a href="{% url 'moreSpecificLeagueView'  'PL' %}">Premier League</a></li></button>
     
      <button> <li><a href="{% url 'moreSpecificLeagueView'  'UEL' %}">Euro 2021</a></li></button>
     
      <button> <li><a href="{% url 'moreSpecificLeagueView'  'EuroCup' %}">UEFA Europa League</a></li></button>

  </div>

  <div class="gri2-2">

    <div class="inner">
      <h1>{{table.0.competition}} {% translate 'Points Table' %}</h1>
    </div>

    <div class="tb">

    <table>

    <tr>
    
      <th colspan="3">{% translate 'Team' %}</th>
      <th>MP</th>
      <th>Won</th>
      <th>Lost</th>
      <th>Tie</th>
      <th>GS</th>
      <th>GC</th>
      <th>GD</th>
      <th>Pts</th>
    
    </tr>
  
   
    {% for value in data %}
      <tr>
        <td width="5%">{{value.pos}}</td>
        <td colspan="2" width="40%">{{value.teamName}}</td>
        <td>{{value.p}}</td>
        <td>{{value.w}}</td>
        <td>{{value.l}}</td>
        <td>{{value.d}}</td>
        <td>{{value.gf}}</td>
        <td>{{value.ga}}</td>
        <td>{{value.gd}}</td>
        <td>{{value.pts}}</td>
      
      </tr>
    {% endfor %}


     {% for value in table %}
        <tr>
         
        <td>{{forloop.counter}}</td>
        <td><img src="#" width="20" height="20"></td><td>{{value.team}}</td>           
        <td>{{value.match_played}}</td> 
        <td>{{value.wins}}</td>
        <td>{{value.lost}}</td>
        <td>{{value.draw}}</td> 
        <td>{{value.goals_for}}</td> 
        <td>{{value.goals_against}}</td>
        <td>{{value.goal_difference}}</td>
        <td>{{value.points}}</td>
      
        </tr>
                    
	    {% endfor %}
    
    
    </table>
    
    
    
    </div>

  </div>
  
<div class="gri3-3">
{% for snippet in snippets %}
<!-- <h3><a href="{% url 'skysports' snippet.path %}">>>> {{snippet.headline}}</a></h3> -->

<h3><a href="#">>>> {{snippet.headline}}</a></h3>
<br>
{% endfor %}


</div>
 
</div>


{% endblock %}

templates/Polls.html
{% extends "homepage.html" %}
{% block title %}Polls{% endblock %}
{% block content %}
{% load static %}
	<link rel="stylesheet" type="text/css" href="{%static 'Polls.css'%}">   

        <!-- For the voting content -->

        <div class="polls">

            <h2 style="text-align: center;">Welcome to the voting sections...Feel free to vote here</h2>

           <div class="vote">
               <h3><u>The Voting questions template tag will be inserted here....</u></h3><br>

               <!-- For options -->

            

                <li><button>Option 1</button></li>
                <li><button>Option 2</button></li>
                <li><button>Option 3</button></li>
                <li><button>Option 4</button></li>
                

             
               </table>
           

           </div>
            

        </div>

{% endblock %}


        

templates/thanks.html
{% load i18n %}
<!DOCTYPE html>
<html>
<head>
	<title>{{trans}}</title>
</head>
<body>
	Choose Your Language
	{% get_current_language as LANGUAGE_CODE %}
	{% get_available_languages as LANGUAGES %}
	{% get_language_info_list for LANGUAGES as languages %}
	{% for language in languages %}
		<ul>
			<a href="#"><li>{{language.name_local}}({{language.code}})</li></a>

		</ul>
	{% endfor %}
</body>
</html>